---
- hosts: linux_workspace
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 86400

    - name: Install prerequisites
      apt:
        pkg:
          - zip
          - dos2unix
          - build-essential
          - ca-certificates
          - curl
          - gnupg
          - gnupg2
          - lsb-release
          - git
          - tree
          - unzip
          - python3-pip
          - python3-virtualenv
        state: latest

    - name: The upper limit on the number of watches that can be created per real user ID
      include_role:
        name: gantsign.inotify
      vars:
        inotify_max_user_watches: 524288

    - name: Install KVM
      include_role:
        name: mrlesmithjr.kvm

    - name: Initialize LXD
      ansible.builtin.shell:
        cmd: lxd init --minimal

    - name: Create a LXD profile
      community.general.lxd_profile:
        name: mji
        description: MJI containers profile
        state: present
        config:
          limits.cpu: "1"
          limits.memory: "2GB"
        devices:
          eth0:
            nictype: bridged
            parent: lxdbr0
            type: nic
          root:
            path: /
            pool: default
            size: 20GB
            type: disk

    - name: Create slave vm
      community.general.lxd_container:
        name: slave-vm
        type: virtual-machine
        state: started
        ignore_volatile_options: true
        wait_for_ipv4_addresses: true
        profiles: ["mji"]
        source:
          protocol: simplestreams
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          alias: ubuntu/kinetic/amd64
        timeout: 600

- hosts:
    - slave-vm
  tasks:
    - name: Provision LXD container
      shell:
        cmd: pwd
