---
- hosts: linux_workspace
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 86400

    - name: Install prerequisites
      apt:
        pkg:
          - zip
          - dos2unix
          - build-essential
          - ca-certificates
          - curl
          - gnupg
          - gnupg2
          - lsb-release
          - git
          - tree
          - unzip
          - python3-pip
          - python3-virtualenv
        state: latest

    - name: The upper limit on the number of watches that can be created per real user ID
      include_role:
        name: gantsign.inotify
      vars:
        inotify_max_user_watches: 524288

    - name: Install KVM
      include_role:
        name: mrlesmithjr.kvm

    - name: Initialize LXD
      ansible.builtin.shell:
        cmd: lxd init --minimal

    - name: Create a LXD profile
      community.general.lxd_profile:
        name: mji
        description: MJI containers profile
        state: present
        config:
          limits.cpu: '1'
          limits.memory: '2GB'
        devices:
          eth0:
            nictype: bridged
            parent: lxdbr0
            type: nic
          root:
            path: /
            pool: default
            size: 20GB
            type: disk

    - name: Create SSH keys directory
      ansible.builtin.file:
        path: ~/.lxd-ssh
        state: directory

    - name: Create SSH key
      community.crypto.openssh_keypair:
        path: ~/.lxd-ssh/id_rsa
      register: lxd_ssh_key

    - name: Create LXD servers
      register: lxd_servers
      loop:
        - slave-vm
      community.general.lxd_container:
        name: '{{ item }}'
        type: virtual-machine
        state: started
        wait_for_container: true
        wait_for_ipv4_addresses: true
        profiles: ['mji']
        source:
          protocol: simplestreams
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          alias: ubuntu/kinetic/cloud
        config:
          cloud-init.user-data: |
            #cloud-config
            ssh_pwauth: false

            users:
            - name: mji
              gecos: MJI User
              groups: users,admin,wheel
              sudo: ALL=(ALL) NOPASSWD:ALL
              shell: /bin/bash
              lock_passwd: true
              ssh_authorized_keys:
                - {{ lxd_ssh_key.public_key }}

            packages:
              - openssh-server
        timeout: 600

    - name: Add LXD server hosts
      loop: '{{ lxd_servers.results }}'
      loop_control:
        label: '{{ item.item }}'
      ansible.builtin.add_host:
        name: '{{ item.item }}'
        groups: containers
        ansible_user: mji
        ansible_host: '{{ item.addresses.eth0[0] }}'
        ansible_ssh_private_key_file: ~/.lxd-ssh/id_rsa
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_become: true

- hosts: containers
  tasks:
    - name: Provision LXD container
      debug:
        msg: 'This is from inside lxd :)'
