# frozen_string_literal: true

source "https://rubygems.org"

group :development do
  gem "vagrant", git: "https://github.com/hashicorp/vagrant.git"
end

group :plugins do
  gem "vagrant-interactive", path: "."
end