Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder ".", "/infrastructure/", owner: "root", group: "root"
  config.vm.synced_folder "../home/vagrant/shared/", "/home/vagrant/shared/"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end
  config.vm.provision "shell", path: "bootstrap.sh"
end
